#!/usr/bin/env python3
"""
generate_bench_frames_cpp.py — emit BOT32/bench_frames.cpp directly from the
healthy-bus capture. Self-contained: carries its own derived MQB CRC magic
tables (so vw_mqb.cpp needs NO edits) and reuses the global MQB_CRC8H2F table.
"""
import csv, statistics, os
from collections import defaultdict, Counter

CSV = r"C:\Users\AntoineLagrandeur\BOT32\DATA input from CAR\OFF to start cluster.csv"
OUT = r"C:\Users\AntoineLagrandeur\BOT32\BOT32\bench_frames.cpp"

T = []
for i in range(256):
    c = i
    for _ in range(8):
        c = ((c << 1) ^ 0x2F) & 0xFF if (c & 0x80) else (c << 1) & 0xFF
    T.append(c)
TINV = [0]*256
for i in range(256): TINV[T[i]] = i

EXCLUDE = {0x3C0,0x641,0x107,0x647,0x040,0x106,0x116,0x65D,0x31E,0x32A,0x30B,0x5BF,0x366}
NAMES = {0x0FD:"ESP_21",0x101:"ESP_02",0x12B:"ESP/Getr",0x147:"Motor",0x31B:"status",
         0x32F:"status",0x394:"WBA_03",0x320:"steer",0x324:"steer",0x3BE:"Motor_14?"}

def group(cid, per):
    if cid in (0x0FD,0x101,0x12B,0x147) or per <= 30: return "ESP/ABS (rapide)"
    if per <= 60: return "Statut 50ms"
    if 0x300 <= cid <= 0x3FF: return "Gateway 100ms"
    if 0x400 <= cid <= 0x5FF: return "Carrosserie/confort"
    return "Lent (>=200ms)"

rows = defaultdict(list)
with open(CSV, newline="") as f:
    r = csv.reader(f); next(r, None)
    for row in r:
        if len(row) < 6: continue
        try:
            ts=int(row[0]); cid=int(row[1],16); ext=row[2].strip().lower(); dlc=int(row[5])
        except ValueError: continue
        if ext=="true": continue
        d=[]
        for i in range(6,14):
            if i<len(row) and row[i].strip()!="":
                try: d.append(int(row[i],16))
                except ValueError: d.append(0)
        rows[cid].append((ts,dlc,d))

all_ts=[ts for v in rows.values() for ts,_,_ in v]
late_start=max(all_ts)-(max(all_ts)-min(all_ts))//10

def counterish(fr):
    inc=tot=0; prev=None
    for ts,dl,d in sorted(fr):
        if len(d)<2: continue
        n=d[1]&0x0F
        if prev is not None:
            tot+=1
            if (prev+1)&0x0F==n: inc+=1
        prev=n
    return tot>0 and inc/tot>0.8

def derive(fr):
    cand=defaultdict(Counter)
    for ts,dl,d in fr:
        if len(d)<8: continue
        ctr=d[1]&0x0F; crc=0xFF
        for b in d[1:8]: crc=T[crc^b]
        magic=TINV[d[0]^0xFF]^crc
        cand[ctr][magic]+=1
    m=[None]*16; ok=True
    for c in range(16):
        if cand[c]:
            top,_=cand[c].most_common(1)[0]; m[c]=top
            if len(cand[c])>1: ok=False
    return m, ok, sum(1 for x in m if x is not None)

magic_tables={}; table=[]
for cid in sorted(rows):
    if cid in EXCLUDE: continue
    fr=rows[cid]
    if len(fr)<50: continue
    ts=sorted(t for t,_,_ in fr)
    deltas=[ts[i+1]-ts[i] for i in range(len(ts)-1)]
    per=int(round(statistics.median(deltas)/1000.0)) if deltas else 100
    if per<=0: per=100
    late=[d for t,dl,d in fr if t>=late_start and len(d)>=1]
    sample=(late[-1] if late else fr[-1][2])
    sample=(sample+[0]*8)[:8]
    dlc=fr[-1][1]
    crc=counterish(fr)
    if crc:
        m,ok,cov=derive(fr)
        if not(ok and cov>=12):
            continue  # skip frames we can't CRC reliably
        magic_tables[cid]=m
    table.append((cid,per,dlc,sample,crc))

table.sort(key=lambda r:(r[1],r[0]))

L=[]
L.append('/*')
L.append(' * bench_frames.cpp — GENERATED by tools/generate_bench_frames_cpp.py')
L.append(' * Bench "lamp killer": live-toggleable healthy-bus status frames replayed')
L.append(' * to extinguish cluster warning lamps on the bench. Steady-state payloads +')
L.append(' * periods + (for E2E frames) the per-ID MQB CRC magic tables are DERIVED from')
L.append(' * the real capture "OFF to start cluster.csv" (lights end OFF). Do not hand-edit;')
L.append(' * re-run the generator to refresh.')
L.append(' *')
L.append(' * Safety: every frame defaults to DISABLED at boot (nothing emitted). The user')
L.append(' * enables them one at a time from the UI to map which frame clears which lamp.')
L.append(' */')
L.append('#include "bench_frames.h"')
L.append('#include "config.h"')
L.append('#include "settings.h"')
L.append('#include "can_handler.h"')
L.append('#include "serial_proto.h"')
L.append('#include "vw_mqb.h"   // for MQB_CRC8H2F[] (global, filled by vw_mqb_init)')
L.append('')
L.append('// ---- Per-ID derived MQB CRC magic tables (from the real capture) ----')
for cid in sorted(magic_tables):
    arr=", ".join("0x%02X"%(x or 0) for x in magic_tables[cid])
    L.append("static const uint8_t MAGIC_0x%03X[16] = { %s };"%(cid,arr))
L.append('')
L.append('static const uint8_t* magic_for(uint16_t id) {')
L.append('  switch (id) {')
for cid in sorted(magic_tables):
    L.append("    case 0x%03X: return MAGIC_0x%03X;"%(cid,cid))
L.append('    default: return nullptr;')
L.append('  }')
L.append('}')
L.append('')
L.append('// Apply 4-bit counter (byte1 low nibble) + recompute CRC into byte0,')
L.append('// using this module\'s own magic tables + the global CRC8H2F table.')
L.append('static void apply_crc(uint16_t id, uint8_t* p, uint8_t len, uint8_t counter) {')
L.append('  if (len < 2) return;')
L.append('  p[1] = (uint8_t)((p[1] & 0xF0) | (counter & 0x0F));')
L.append('  const uint8_t* k = magic_for(id);')
L.append('  uint8_t crc = 0xFF;')
L.append('  for (uint8_t i = 1; i < len; i++) crc = MQB_CRC8H2F[crc ^ p[i]];')
L.append('  if (k) crc = MQB_CRC8H2F[crc ^ k[p[1] & 0x0F]];')
L.append('  p[0] = (uint8_t)(crc ^ 0xFF);')
L.append('}')
L.append('')
L.append('// ---- Candidate frame table (DERIVED) ----')
L.append('struct BenchFrame {')
L.append('  uint16_t id; uint16_t period_ms; uint8_t dlc;')
L.append('  uint8_t  tmpl[8]; bool needs_crc; const char* group;')
L.append('};')
L.append('static const BenchFrame FRAMES[] = {')
for cid,per,dlc,sample,crc in table:
    pl=", ".join("0x%02X"%b for b in sample)
    nm=NAMES.get(cid,"")
    L.append('  { 0x%03X, %3d, %d, {%s}, %s, "%s" },%s'%(
        cid,per,dlc,pl,"true" if crc else "false",group(cid,per),
        ("  // "+nm) if nm else ""))
L.append('};')
L.append('static const uint8_t N_FRAMES = sizeof(FRAMES)/sizeof(FRAMES[0]);')
L.append('')
L.append('static bool     g_enabled[N_FRAMES];')
L.append('static uint32_t g_last_ms[N_FRAMES];')
L.append('static uint8_t  g_counter[N_FRAMES];')
L.append('')
L.append('void bench_frames_init() {')
L.append('  for (uint8_t i = 0; i < N_FRAMES; i++) { g_enabled[i]=false; g_last_ms[i]=0; g_counter[i]=0; }')
L.append('}')
L.append('')
L.append('uint8_t bench_frames_count() { return N_FRAMES; }')
L.append('')
L.append('uint16_t bench_frames_id(uint8_t idx)        { return idx<N_FRAMES?FRAMES[idx].id:0; }')
L.append('uint16_t bench_frames_period(uint8_t idx)     { return idx<N_FRAMES?FRAMES[idx].period_ms:0; }')
L.append('bool     bench_frames_needs_crc(uint8_t idx)  { return idx<N_FRAMES?FRAMES[idx].needs_crc:false; }')
L.append('const char* bench_frames_group(uint8_t idx)   { return idx<N_FRAMES?FRAMES[idx].group:""; }')
L.append('bool     bench_frames_enabled(uint8_t idx)    { return idx<N_FRAMES?g_enabled[idx]:false; }')
L.append('')
L.append('bool bench_frames_set_enabled(uint8_t idx, bool on) {')
L.append('  if (idx >= N_FRAMES) return false;')
L.append('  g_enabled[idx] = on;')
L.append('  return true;')
L.append('}')
L.append('')
L.append('void bench_frames_all_off() {')
L.append('  for (uint8_t i = 0; i < N_FRAMES; i++) g_enabled[i] = false;')
L.append('}')
L.append('')
L.append('// Send each ENABLED frame at its period. Call from bench_test_tick() only')
L.append('// (i.e. bench mode active + tx_enabled). Bus = the configured bench bus.')
L.append('void bench_frames_tick(uint32_t now) {')
L.append('  CanChannel ch = (settings_get().bench_test_bus == 1) ? CAN_OBD2 : CAN_CLUSTER;')
L.append('  for (uint8_t i = 0; i < N_FRAMES; i++) {')
L.append('    if (!g_enabled[i]) continue;')
L.append('    if (now - g_last_ms[i] < FRAMES[i].period_ms) continue;')
L.append('    g_last_ms[i] = now;')
L.append('    CanFrame f;')
L.append('    f.id = FRAMES[i].id;')
L.append('    f.len = FRAMES[i].dlc;')
L.append('    for (uint8_t b = 0; b < 8; b++) f.data[b] = FRAMES[i].tmpl[b];')
L.append('    if (FRAMES[i].needs_crc) {')
L.append('      apply_crc(FRAMES[i].id, f.data, f.len, g_counter[i]);')
L.append('      g_counter[i] = (uint8_t)((g_counter[i] + 1) & 0x0F);')
L.append('    }')
L.append('    if (can_send(ch, f)) serial_proto_report_tx(ch, f);')
L.append('  }')
L.append('}')
L.append('')

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT,"w",newline="\n") as f:
    f.write("\n".join(L))
print("wrote %s"%OUT)
print("frames: %d   crc-tables: %d"%(len(table),len(magic_tables)))
print("groups:", sorted(set(group(c,p) for c,p,_,_,_ in table)))
